language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
matrix:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls -v
